---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: kiranreddy678/b1:dbimage
   ports:
     - "3306:3306"

 application:
   image: kiranreddy/b1:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
